version: '3.8'

services:
  php:
    image: php:8.2-fpm
    container_name: yii2-php
    volumes:
      - .:/var/www/html
    networks:
      - yii2-network

  nginx:
    image: nginx:alpine
    container_name: yii2-nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - yii2-network

  mysql:
    image: mysql:8.0
    container_name: yii2-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - yii2-network

volumes:
  db_data:

networks:
  yii2-network:
    driver: bridge
