version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./app:/var/www/html
    depends_on:
      - php
    networks:
      - webnet

  php:
    image: php:8.2-fpm
    container_name: php
    volumes:
      - ./app:/var/www/html
    networks:
      - webnet

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-yourrootpswd}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-yii2-news}
      MYSQL_USER: ${MYSQL_USER:-yii2user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-youruserpswd}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
