<<<<<<< Updated upstream
version: '3.8'

services:
  php:
    image: php:8.2-fpm
    container_name: yii2-php
    volumes:
      - .:/var/www/html
    networks:
      - yii2-network

  nginx:
    image: nginx:alpine
    container_name: yii2-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - php
    networks:
      - yii2-network
=======
version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "20080:80"
    volumes:
      # Re-use local composer cache via host-volume (Linux-friendly)
      - ${HOME}/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./frontend:/app
    depends_on:
      - mysql

  backend:
    build: ./backend
    ports:
      - "21080:80"
    volumes:
      - ${HOME}/.composer-docker/cache:/root/.composer/cache:delegated
      - ./backend:/app
    depends_on:
      - mysql
>>>>>>> Stashed changes

  mysql:
    image: mysql:8.0
    container_name: yii2-mysql
    environment:
<<<<<<< Updated upstream
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - yii2-network

volumes:
  db_data:

networks:
  yii2-network:
    driver: bridge
=======
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_DATABASE: yii2advanced
      MYSQL_USER: yii2advanced
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
>>>>>>> Stashed changes
