<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(not set)' => '',
    'A password will be generated automatically if not provided' => '',
    'Abaikan dan jangan membalas email ini seandainya anda merasa tidak pernah mendaftar.' => '',
    'Account details' => '',
    'Akun anda di {0} telah berhasil dibuat.' => '',
    'Are you sure you want to block this user?' => '',
    'Are you sure you want to confirm this user?' => '',
    'Are you sure you want to delete this user?' => '',
    'Are you sure you want to switch to this user for the rest of this Session?' => '',
    'Are you sure you want to unblock this user?' => '',
    'Are you sure?' => '',
    'Assignments' => '',
    'Become this user' => '',
    'Block' => '',
    'Block status' => '',
    'Blocked at {0, date, MMMM dd, YYYY HH:mm}' => '',
    'Confirm' => '',
    'Confirmation' => '',
    'Confirmation status' => '',
    'Confirmed' => '',
    'Confirmed at {0, date, MMMM dd, YYYY HH:mm}' => '',
    'Continue' => '',
    'Create' => '',
    'Create a user account' => '',
    'Credentials will be sent to the user by email' => '',
    'Delete' => '',
    'Didn\'t receive confirmation message?' => '',
    'Don\'t have an account? Sign up!' => '',
    'Forgot password?' => '',
    'Generate and send new password to user' => '',
    'Hello' => '',
    'If you already registered, sign in and connect this account on settings page' => '',
    'If you cannot click the link, please try pasting the text into your browser' => '',
    'If you did not make this request you can ignore this email' => '',
    'In order to complete your registration, please click the link below' => '',
    'In order to complete your request, please click the link below' => '',
    'In order to finish your registration, we need you to enter following fields' => '',
    'Information' => '',
    'Jika ada pertanyaan, silahkan menghubungi narahubung yang tertera di web.' => '',
    'Jika link tidak bisa di-klik, coba di-copy dan paste di halaman web browser anda.' => '',
    'Kami telah membuatkan password untuk anda ' => '',
    'Manage users' => '',
    'Never' => '',
    'New permission' => '',
    'New role' => '',
    'New user' => '',
    'Not blocked' => '',
    'Password' => '',
    'Password is not necessary because the module is in DEBUG mode.' => '',
    'Permissions' => '',
    'Please click the link below to complete your password reset' => '',
    'Profile details' => '',
    'Register a new membership' => '',
    'Registration IP' => '',
    'Registration time' => '',
    'Request new confirmation message' => '',
    'Roles' => '',
    'Save' => '',
    'Sign in' => '',
    'Sign up' => '',
    'Terima Kasih' => '',
    'Thank you for signing up on {0}' => '',
    'Unblock' => '',
    'Unconfirmed' => '',
    'Untuk bisa menyelesaikan proses pendaftaran, silahkan klik link berikut : ' => '',
    'Update' => '',
    'Update user account' => '',
    'Users' => '',
    'We have generated a password for you' => '',
    'We have received a request to change the email address for your account on {0}' => '',
    'We have received a request to reset the password for your account on {0}' => '',
    'You can assign multiple roles or permissions to user by using the form below' => '',
    'Your account on {0} has a new password' => '',
    'Your account on {0} has been created' => '',
    'resend' => '',
    'signin' => '',
    '{0, date, MMMM dd, YYYY HH:mm}' => '',
];
